#!/bin/bash

# This script builds and launches trace, rebuilding and restarting
# the trace server if its source files change.

# Ensure that background processes die with script exit
trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT

full_restart() {
  kill -9 $(jobs -pr)
  make clean
  make
  ./openpixelcontrol/bin/gl_server -l layout.json &
  ./trace -layout layout.json &
  PTRACE=$!
}

restart_trace() {
  kill -9 $PTRACE
  rm ./trace
  rm -rf **.dSYM
  make trace
  ./trace -layout layout.json &
  PTRACE=$!
}

full_restart

fswatch -0 ./ | while read -d "" event; do
  if [[ ${event} =~ (/Makefile|\.py)$ ]]; then
    full_restart;
  elif [[ ${event} =~ (\.cpp|\.h)$ ]]; then
    restart_trace
  fi;
done

