#!/bin/bash

# Recompile if -r flag is passed
if [ "$1" == "-r" ]; then
  rm ./trace
  rm -rf **.dSYM
  make trace && clear || exit
fi

# Launch trace
while true; do
  echo shaders/* | entr -c -d -r ./scripts/run;
done
